# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2.1"

networks:
  test:
    name: insurance_network

services:
  ca_org4:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org4
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7111
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17111
    ports:
      - "7111:7111"
      - "17111:17111"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org4:/etc/hyperledger/fabric-ca-server
    container_name: ca_org4
    networks:
      - test

  ca_org5:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org5
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7112
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17112
    ports:
      - "7112:7112"
      - "17112:17112"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org5:/etc/hyperledger/fabric-ca-server
    container_name: ca_org5
    networks:
      - test

  ca_aaui:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aaui
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7110
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17110
    ports:
      - "7110:7110"
      - "17110:17110"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/aauiOrg:/etc/hyperledger/fabric-ca-server
    container_name: ca_aaui
    networks:
      - test
