# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  test:
    name: fabric_test

services:

  ca_prudential:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-prudential
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11053
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11053
    ports:
      - "11053:11053"
      - "17053:17053"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/prudential:/etc/hyperledger/fabric-ca-server
    container_name: ca_prudential
    networks:
      - test

  ca_manulife:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-manulife
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=11054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11054
    ports:
      - "11054:11054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/manulife:/etc/hyperledger/fabric-ca-server
    container_name: ca_manulife
    networks:
      - test

  ca_aaui:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-aaui
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=12052
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12052
    ports:
      - "12052:12052"
      - "18052:18052"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/aaui:/etc/hyperledger/fabric-ca-server
    container_name: ca_aaui
    networks:
      - test
