#defines de version of the docker-compose
version: '3.7'

networks:
  swarm-dteti:
    external: true
    driver: overlay

services:
  arsada:
    # container_name: orderer.arsada.org
    image: hyperledger/fabric-orderer:2.2
    dns_search: https://arsada.org
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ARSADAMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:5051
      - ORDERER_GENERAL_LISTENPORT=5050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 5050:5050
      - 5051:5051
    networks:
      - swarm-dteti
    volumes:
      #- type: volume
       # source: swarm_shared_volume
        #target: /mnt/volumes/3697e77d11dfa39fed4477da5e38f9d6
        #volume:
          #nocopy: true
          #driver: vieux/sshfs
          #driver_opts:
           # sshcmd: "root@10.42.29.109:/home/shared/data"
           # password: "gdputra"
      - ~/projects/dteti-sys-rsch/slinmac/channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ~/projects/dteti-sys-rsch/slinmac/organizations/ordererOrganizations/arsada.org/orderers/orderer.arsada.org/msp:/var/hyperledger/orderer/msp
      - ~/projects/dteti-sys-rsch/slinmac/organizations/ordererOrganizations/arsada.org/orderers/orderer.arsada.org/tls:/var/hyperledger/orderer/tls
    deploy:
        mode: global
        placement:
          constraints: [node.hostname == guntur-labse]

  arssi:
    # container_name: orderer.arssi.org
    image: hyperledger/fabric-orderer:2.2
    dns_search: https://arssipusat.org/
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ARSSIMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:6061
      - ORDERER_GENERAL_LISTENPORT=6050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 6050:6050
      - 6061:6061
    networks:
      - swarm-dteti
    volumes:
      #- type: volume
        #source: swarm_shared_volume
        #target: /mnt/volumes/3697e77d11dfa39fed4477da5e38f9d6
        #volume:
          #nocopy: true
          #driver: vieux/sshfs
          #driver_opts:
            #sshcmd: "root@10.42.29.109:/home/shared/data"
            #password: "gdputra"
      - ~/projects/dteti-sys-rsch/slinmac/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ~/projects/dteti-sys-rsch/slinmac/organizations/ordererOrganizations/arssi.org/orderers/orderer.arssi.org/msp:/var/hyperledger/orderer/msp
      - ~/projects/dteti-sys-rsch/slinmac/organizations/ordererOrganizations/arssi.org/orderers/orderer.arssi.org/tls:/var/hyperledger/orderer/tls
    deploy:
        mode: global
        placement:
          constraints: [node.hostname == guntur-labse]

  sardjito:
    # container_name: peer0.sardjito.co.id
    image: hyperledger/fabric-peer:2.2
    dns_search: https://sardjito.co.id/
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=SardjitoMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_pharma-chain
      - CORE_PEER_ID=peer0.sardjito.co.id
      - CORE_PEER_ADDRESS=peer0.sardjito.co.id:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sardjito.co.id:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ta3.com:9051
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sardjito.co.id:7051
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    ports:
      - 7051:7051
    volumes:
      #- type: volume
        #source: swarm_shared_volume
        #target: /mnt/volumes/3697e77d11dfa39fed4477da5e38f9d6
        #volume:
          #nocopy: true
          #driver: vieux/sshfs
          #driver_opts:
            #sshcmd: "root@10.42.29.109:/home/shared/data"
            #password: "gdputra"
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/sardjito.co.id/peers/peer0.sardjito.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/sardjito.co.id/peers/peer0.sardjito.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - ./channel/:/etc/hyperledger/channel/
    deploy:
        mode: global
        placement:
          constraints: [node.hostname == guntur-labse]
    networks:
      - swarm-dteti
  
  rscm:
    # container_name: peer0.rscm.co.id
    image: hyperledger/fabric-peer:2.2
    dns_search: https://www.rscm.co.id/
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=RSCMMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_pharma-chain
      - CORE_PEER_ID=peer0.rscm.co.id
      - CORE_PEER_ADDRESS=peer0.rscm.co.id:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rscm.co.id:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rscm.co.id:8051
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    ports:
      - 8051:8051
    volumes:
      #- type: volume
        #source: swarm_shared_volume
        #target: /mnt/volumes/3697e77d11dfa39fed4477da5e38f9d6
        #volume:
          #nocopy: true
          #driver: vieux/sshfs
          #driver_opts:
            #sshcmd: "root@10.42.29.109:/home/shared/data"
            #password: "gdputra"
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/rscm.co.id/peers/peer0.rscm.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/rscm.co.id/peers/peer0.rscm.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
      # - ./channel/:/etc/hyperledger/channel/
    deploy:
        mode: global
        placement:
          constraints: [node.hostname == guntur-labse]
    networks:
      - swarm-dteti

  dharmais:
    # container_name: peer0.dharmais.co.id
    image: hyperledger/fabric-peer:2.2
    dns_search: https://dharmais.co.id/
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=DharmaisMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=docker_pharma-chain
      - CORE_PEER_ID=peer0.dharmais.co.id
      - CORE_PEER_ADDRESS=peer0.dharmais.co.id:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.dharmais.co.id:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ta3.com:9051
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_METRICS_PROVIDER=prometheus
      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/crypto/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/crypto/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/crypto/peer/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
    ports:
      - 9051:9051
    volumes:
      #- type: volume
        #source: swarm_shared_volume
        #target: /mnt/volumes/3697e77d11dfa39fed4477da5e38f9d6
        #volume:
          #nocopy: true
          #driver: vieux/sshfs
          #driver_opts:
            #sshcmd: "root@10.42.29.109:/home/shared/data"
            #password: "gdputra"
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/dharmais.co.id/peers/peer0.dharmais.co.id/msp:/etc/hyperledger/crypto/peer/msp
      - ~/projects/dteti-sys-rsch/slinmac/organizations/peerOrganizations/dharmais.co.id/peers/peer0.dharmais.co.id/tls:/etc/hyperledger/crypto/peer/tls
      - /var/run/:/host/var/run/
       - ./channel/:/etc/hyperledger/channel/
    deploy:
        mode: global
        placement:
          constraints: [node.hostname == guntur-labse]
    networks:
      - swarm-dteti
