version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - 2023:2023
    networks:
      - swarm-dteti
    deploy:
        mode: replicated
        replicas: 2
        placement:
          constraints: [node.hostname == guntur-labse]
  web2:
    image: nginx:alpine
    ports:
      - 4023:4023
    networks:
      - swarm-dteti
    deploy:
        mode: replicated
        replicas: 2
        placement:
          constraints: [node.hostname == win-labse]

networks:
  swarm-dteti:
    external: true