version: '3.8'

services:
  ## Database Off Chain
  pharmachain_mongodb:
    container_name: pharmachain_mongodb
    image: mongo:latest
    restart: always
    ports:
      - protocol: tcp
        published: 27017
        target: 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dteti
      MONGO_INITDB_ROOT_PASSWORD: mongodteti
      MONGO_INITDB_DATABASE: healthinsurance
    volumes:
      - mongodb_data:/data/db
    networks: 
      - blockchain
      - health-insurance-net

  pharmachain_postgres:
    container_name: pharmachain_postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: dteti
      POSTGRES_PASSWORD: postgresdteti
      POSTGRES_DB: hospitals
    ports:
      - protocol: tcp
        published: 5432
        target: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blockchain
      - hospital-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dteti@dteti.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin:/home/gdputra/shared/data/pgadmin
    networks:
      - hospital-net

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.42.29.133,rw,nolock,soft"
      device: ":/home/gdputra/shared/data/mongodb"
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.42.29.133,rw,nolock,soft"
      device: ":/home/gdputra/shared/data/postgres"
  pgadmin_data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.42.29.133,rw,nolock,soft"
      device: ":/home/gdputra/shared/data/pgadmin"

networks:
  blockchain:
    external: true
    driver: bridge
  hospital-net:
    name: hospital-net
    driver: bridge
  health-insurance-net:
    name: health-insurance-net
    driver: bridge
