# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

volumes:
  orderer.arsada.org:
  peer0.sardjito.arsada.org:
  peer0.dharmais.arsada.org:

networks:
  test:
    name: fabric_test

services:

  orderer.arsada.org:
    container_name: orderer.arsada.org
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7051
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.arsada.org:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/arsada.org/orderers/orderer.arsada.org/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/arsada.org/orderers/orderer.arsada.org/tls/:/var/hyperledger/orderer/tls
        - orderer.arsada.org:/var/hyperledger/production/orderer
    ports:
      - 7051:7051
      - 9443:9443
    networks:
      - test

  peer0.sardjito.arsada.org:
    container_name: peer0.sardjito.arsada.org
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.sardjito.arsada.org
      - CORE_PEER_ADDRESS=peer0.sardjito.arsada.org:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sardjito.arsada.org:10061
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10061
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sardjito.arsada.org:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sardjito.arsada.org:10051
      - CORE_PEER_LOCALMSPID=SardjitoMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.sardjito.arsada.org:9444
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/sardjito.arsada.org/peers/peer0.sardjito.arsada.org/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/sardjito.arsada.org/peers/peer0.sardjito.arsada.org/tls:/etc/hyperledger/fabric/tls
        - peer0.sardjito.arsada.org:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10051:10051
      - 9444:9444
    networks:
      - test

  peer0.dharmais.arsada.org:
    container_name: peer0.dharmais.arsada.org
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.dharmais.arsada.org
      - CORE_PEER_ADDRESS=peer0.dharmais.arsada.org:10052
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_CHAINCODEADDRESS=peer0.dharmais.arsada.org:10062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10062
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dharmais.arsada.org:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dharmais.arsada.org:10052
      - CORE_PEER_LOCALMSPID=DharmaisMSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.dharmais.arsada.org:9445
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/dharmais.arsada.org/peers/peer0.dharmais.arsada.org/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/dharmais.arsada.org/peers/peer0.dharmais.arsada.org/tls:/etc/hyperledger/fabric/tls
        - peer0.dharmais.arsada.org:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 10052:10052
      - 9445:9445
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.sardjito.arsada.org
      - peer0.dharmais.arsada.org
    networks:
      - test
